[package]
name = "sandkasten-client"
version = "0.0.1"
edition = "2021"
publish = true

[features]
default = ["reqwest"]
reqwest = ["dep:reqwest", "dep:url"]
blocking = ["reqwest", "reqwest/blocking"]
poem-openapi = ["dep:poem-openapi"]

[dependencies]
poem-openapi = { version = "2.0.26", default-features = false, optional = true, features = ["uuid"] }
reqwest = { version = "0.11.17", default-features = false, optional = true, features = ["json", "rustls-tls"] }
serde.workspace = true
thiserror.workspace = true
url = { version = "2.3.1", default-features = false, optional = true }
uuid.workspace = true
