host = "0.0.0.0"
port = 8000
server = "/"

redis_url = "redis://127.0.0.1:6379/0"
cache_ttl = 3600

programs_dir = "/programs"
jobs_dir = "/jobs"

program_ttl = 600
prune_programs_interval = 60

max_concurrent_jobs = 64

[compile_limits]
cpus = 1
time = 30  # seconds
memory = 4096  # mb
tmpfs = 256  # mb
filesize = 16  # mb
file_descriptors = 256
processes = 256
stdout_max_size = 65536
stderr_max_size = 65536
network = false

[run_limits]
cpus = 1
time = 5  # seconds
memory = 3072  # mb
tmpfs = 256  # mb
filesize = 16  # mb
file_descriptors = 256
processes = 64
stdout_max_size = 65536
stderr_max_size = 65536
network = false
