version: '3.10'

services:
  sandkasten:
    image: ghcr.io/defelo/sandkasten
    restart: always
    init: true
    privileged: true
    environment:
      RUST_LOG: info,sandkasten=debug
      REDIS_URL: redis://redis:6379/0
    volumes:
      - ./config.toml:/config.toml:ro
    tmpfs:
      - /jobs:uid=65534,gid=65534
      - /programs:exec,uid=65534,gid=65534
    ports:
      - 127.0.0.1:8000:8000
  redis:
    image: redis:alpine
    restart: always
